# Generated by Django 6.0 on 2026-03-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'posts',
                'indexes': [models.Index(fields=['event_id'], name='posts_event_i_4d9cbf_idx'), models.Index(fields=['user_id'], name='posts_user_id_05c508_idx'), models.Index(fields=['category'], name='posts_categor_c9aadc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'db_table': 'comments',
                'indexes': [models.Index(fields=['post'], name='comments_post_id_7ee550_idx'), models.Index(fields=['user_id'], name='comments_user_id_8613ff_idx'), models.Index(fields=['created_at'], name='comments_created_d5740c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('reaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('type', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=10)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post')),
            ],
            options={
                'db_table': 'post_reactions',
                'indexes': [models.Index(fields=['post'], name='post_reacti_post_id_3b6863_idx'), models.Index(fields=['user_id'], name='post_reacti_user_id_f8e0ae_idx'), models.Index(fields=['type'], name='post_reacti_type_4278a3_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'post'), name='uq_post_reactions_user_post')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('reason_category', models.CharField(max_length=30)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['post'], name='reports_post_id_246508_idx'), models.Index(fields=['user_id'], name='reports_user_id_224fd3_idx'), models.Index(fields=['reason_category'], name='reports_reason__0a822f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'post'), name='uq_reports_user_post')],
            },
        ),
    ]
